[build]
  command = "npm run build"
  publish = ".next"
  functions = ".netlify/functions"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "false"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# For Next.js API routes support
[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

# Handle client-side routing for Next.js
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200